STANDARD_DEDUCTION = 50000
TWO_LAKH_FIFTY_THOUSAND = 250000
THREE_LAKHS = 300000
FIVE_LAKHS = 500000
SIX_LAKHS = 600000
SEVEN_LAKHS = 700000
NINE_LAKHS = 900000
TEN_LAKHS = 1000000
TWELVE_LAKHS = 1200000
FIFTEEN_LAKHS = 1500000

NIL = 'NIL'
ZERO ='0'

ZERO_TO_TWO_POINT_FIVE_LAKH = 'Up to Rs. 2.5 lakh'
ZERO_TO_FIVE_LAKH = 'Up to Rs. 5 lakh'
TWO_POINT_FIVE_TO_FIVE_LAKH = 'Rs. 2.5 lakh - Rs. 5 lakh'
FIVE_TO_TEN_LAKH = 'Rs. 5 lakh - Rs. 10 lakh'
GREATER_THAN_TEN_LAKH = '> Rs. 10 lakh'

FIVE_PERCENT_RANGE = '5%'
TWENTY_PERCENT_RANGE = '20%'
THIRTY_PERCENT_RANGE = '30%'

ZERO_TO_THREE_LAKH = 'Up to Rs. 3 lakh'
ZERO_TO_SEVEN_LAKH = 'Up to Rs. 7 lakh'
THREE_TO_SIX_LAKH = 'Rs. 3 lakh - Rs. 6 lakh'
SIX_TO_NINE_LAKH = 'Rs. 6 lakh - Rs. 9 lakh'
NINE_TO_TWELVE_LAKH = 'Rs. 9 lakh - Rs. 12 lakh'
TWELVE_TO_FIFTEEN_LAKH = 'Rs. 12 lakh - Rs. 15 lakh'
GREATER_THAN_FIFTEN_LAKH = '> Rs. 15 lakh'

FIVE_PERCENT_RANGE = '5%'
TEN_PERCENT_RANGE = '10%'
FIFTEN_PERCENT_RANGE = '15%'
TWENTY_PERCENT_RANGE = '20%'
THIRTY_PERCENT_RANGE = '30%'

OLD_TAX_HEADERS = ["Old Income tax slab", "Age < 60", "Amount"]
NEW_TAX_HEADERS = ["New Income tax slab", "Age < 60", "Amount"]
